language: python


python: 
  - "3.6"

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda

install:
  - conda env create -f environment.yml
  - source activate test

script:
  - pylint -E eclingo.py eclingo/main.py eclingo/preprocessor/preprocessor.py eclingo/parser/parser.py eclingo/solver/solver.py eclingo/postprocessor/postprocessor.py test/test_main.py
  - python3 -m pytest --durations=5 -vv