language: python


include:

  - python: 3.6

before_install:

  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes conda

install:

  - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
  - source activate test

  - conda install --yes -c potassco clingo
  - conda install --yes -c anaconda pylint
  - conda install --yes -c anaconda pytest 

script:

  - pylint -E eclingo/eclingo.py eclingo/parser/parser.py eclingo/solver/solver.py test/test_main.py
  - python3 -m pytest --durations=3