language: python


python: 
  - "3.6"

os:
  - linux

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda

install:
  - conda env create -f environment.yml
  - conda activate eclingo
  - python3 -m pip install .

script:
  - pylama
  - python3 -m pytest --durations=5 -vv